### ISSUE TITLE
rotorInertiaについて

### ISSUE THREAD

**Issue by YoheiKakiuchi** [jvrc/model#3]
JVRC-1の各関節にrotorInertiaが設定されていますが、この値がずいぶん大きいのではないかと思います。
（リンクの慣性よりも,rotorInertiaの方が何十倍も大きいところがある）
実機があるものではないので、間違っているということはないのですが、どういう想定で設定された値でしょうか？
また、これぐらいの値を設定しないとシミュレータで振動してしまうということがあったりしますでしょうか？

また、モデルファイルの定義としてrotorInertiaはモーターの軸を回転させるときの慣性という理解であっていますでしょうか？

**Comment by fkanehiro** [comment]
実在するモータ及び減速機の組み合わせに基いて値を設定しています。
具体的な組み合わせは非公開のため、gearRatioを1として、rotorInertiaにはモータのローター慣性×ギヤ比×ギヤ比の値を設定しています。

**Comment by YoheiKakiuchi** [comment]
ありがとうございます。

rotorInertiaの換算がローター慣性×ギヤ比と勘違いしておりました。

2015年7月25日 7:56 Fumio KANEHIRO notifications@github.com:
