### ISSUE TITLE
JVRC-1の記述ミス？

### ISSUE THREAD

**Issue by s-creek** [jvrc/model#4]
下記のジョイントについて，速度リミットに lvlimit がなく uvlimit が二つ書かれているみたいです．
R_ANKLE_P
WAIST_Y
R_UTHUMB
R_UINDEX
R_ULITTLE
L_UTHUMB
L_UINDEX
L_ULITTLE

**Comment by fkanehiro** [comment]
ご指摘ありがとうございます。修正しました。
